# WSO2 API Manager Configuration
# This file defines APIs to be created and published

apis:
  - name: "Forex Service API"
    context: "/api/forex"
    version: "1.0.0"
    backend_url: "http://forex:8000"
    description: "Forex rate conversion service"
    tags: ["forex", "currency"]

  - name: "Profile Service API"
    context: "/api/profile"
    version: "1.0.0"
    backend_url: "http://profile:8000"
    description: "User profile management service"
    tags: ["profile", "user"]

  - name: "Payment Service API"
    context: "/api/payment"
    version: "1.0.0"
    backend_url: "http://payment:8000"
    description: "Payment processing service"
    tags: ["payment", "transaction"]

  - name: "Ledger Service API"
    context: "/api/ledger"
    version: "1.0.0"
    backend_url: "http://ledger:8000"
    description: "Financial ledger service"
    tags: ["ledger", "accounting"]

  - name: "Wallet Service API"
    context: "/api/wallet"
    version: "1.0.0"
    backend_url: "http://wallet:8000"
    description: "Digital wallet service"
    tags: ["wallet", "balance"]

  - name: "Rule Engine Service API"
    context: "/api/rules"
    version: "1.0.0"
    backend_url: "http://rule-engine:8000"
    description: "Business rules engine service"
    tags: ["rules", "engine"]

# Application configuration
application:
  name: "DefaultApplication"
  throttling_policy: "Unlimited"

# Subscription configuration
subscriptions:
  - api_name: "Forex Service API"
    throttling_policy: "Unlimited"
  - api_name: "Profile Service API"
    throttling_policy: "Unlimited"
  - api_name: "Payment Service API"
    throttling_policy: "Unlimited"
  - api_name: "Ledger Service API"
    throttling_policy: "Unlimited"
  - api_name: "Wallet Service API"
    throttling_policy: "Unlimited"
  - api_name: "Rule Engine Service API"
    throttling_policy: "Unlimited"
