[server]
hostname = "localhost"
node_ip = "127.0.0.1"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.apim_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2AM_DB;DB_CLOSE_ON_EXIT=FALSE"
username = "wso2carbon"
password = "wso2carbon"

[database.shared_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE"
username = "wso2carbon"
password = "wso2carbon"

# WSO2 Identity Server Integration (Key Manager)
[[apim.key_manager]]
name = "WSO2 Identity Server"
type = "WSO2-IS"
display_name = "WSO2 Identity Server"
description = "Financial-grade Identity Server for PCI-DSS compliance"
enabled = true

[apim.key_manager.configuration]
ServerURL = "https://wso2is:9444/services/"
Username = "admin"
Password = "admin"
TokenURL = "https://wso2is:9444/oauth2/token"
RevokeURL = "https://wso2is:9444/oauth2/revoke"
IntrospectURL = "https://wso2is:9444/oauth2/introspect"
UserInfoURL = "https://wso2is:9444/oauth2/userinfo"
AuthorizeURL = "https://wso2is:9444/oauth2/authorize"
TokenValidation = "INTROSPECT"

# JWT Token Validation - WSO2 IS Integration
[apim.jwt]
enable = true
encoding = "base64"
header = "X-JWT-Assertion"
signing_algorithm = "RS256"
enable_user_claims = true
claim_dialect = "http://wso2.org/claims"

[[apim.jwt.issuer]]
issuer = "https://localhost:9444/oauth2/token"
jwks_endpoint = "https://wso2is:9444/oauth2/jwks"
validate_subscribed_apis = false
consumer_key_claim = "client_id"
scopes_claim = "scope"

# Claim mappings - WSO2 IS standard claims
[[apim.jwt.issuer.claim_mapping]]
remote_claim = "sub"
local_claim = "http://wso2.org/claims/username"

[[apim.jwt.issuer.claim_mapping]]
remote_claim = "email"
local_claim = "http://wso2.org/claims/emailaddress"

# CORS Configuration
[apim.cors]
allow_origins = "*"
allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction","X-JWT-Assertion"]
allow_credentials = false

# OAuth Configuration
[apim.oauth_config]
enable_outbound_auth_header = false

# Gateway Environment Configuration (REQUIRED for API deployment)
[[apim.gateway.environment]]
name = "Default"
type = "hybrid"
display_in_api_console = true
description = "Default Gateway Environment"
ws_endpoint = "ws://localhost:9099"
wss_endpoint = "wss://localhost:8099"
http_endpoint = "http://localhost:8280"
https_endpoint = "https://localhost:8243"
