[server]
hostname = "localhost"
node_ip = "127.0.0.1"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.apim_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2AM_DB;DB_CLOSE_ON_EXIT=FALSE"
username = "wso2carbon"
password = "wso2carbon"

[database.shared_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE"
username = "wso2carbon"
password = "wso2carbon"

# JWT Token Validation - Keycloak Integration
[apim.jwt]
enable = true
encoding = "base64"
header = "X-JWT-Assertion"
signing_algorithm = "RS256"
enable_user_claims = true
claim_dialect = "http://wso2.org/claims"

[[apim.jwt.issuer]]
issuer = "https://auth.127.0.0.1.sslip.io/realms/innover"
jwks_endpoint = "https://auth.127.0.0.1.sslip.io/realms/innover/protocol/openid-connect/certs"
validate_subscribed_apis = false
consumer_key_claim = "azp"
scopes_claim = "scope"

# Claim mappings - Keycloak to WSO2
[[apim.jwt.issuer.claim_mapping]]
remote_claim = "preferred_username"
local_claim = "http://wso2.org/claims/username"

[[apim.jwt.issuer.claim_mapping]]
remote_claim = "email"
local_claim = "http://wso2.org/claims/emailaddress"

# CORS Configuration
[apim.cors]
allow_origins = "*"
allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction","X-JWT-Assertion"]
allow_credentials = false

# OAuth Configuration
[apim.oauth_config]
enable_outbound_auth_header = false

# Gateway Environment Configuration (REQUIRED for API deployment)
[[apim.gateway.environment]]
name = "Default"
type = "hybrid"
display_in_api_console = true
description = "Default Gateway Environment"
ws_endpoint = "ws://localhost:9099"
wss_endpoint = "wss://localhost:8099"
http_endpoint = "http://localhost:8280"
https_endpoint = "https://localhost:8243"
