[server]
hostname = "wso2is"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.identity_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2IDENTITY_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
username = "wso2carbon"
password = "wso2carbon"

[database.shared_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
username = "wso2carbon"
password = "wso2carbon"

[keystore.primary]
file_name = "wso2carbon.p12"
password = "wso2carbon"
type="PKCS12"

[truststore]
file_name="client-truststore.p12"
password="wso2carbon"
type="PKCS12"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

# Disable mutual TLS client authentication to avoid "more than one authentication method" error
[[event_listener]]
id = "mutual_tls_authenticator"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.carbon.identity.oauth2.token.handler.clientauth.mutualtls.MutualTLSClientAuthenticator"
order = "158"
enable = false

# Token revocation event handler - notifies APIM about token operations
[[event_listener]]
id = "token_revocation"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.is.notification.ApimOauthEventInterceptor"
order = 1
[event_listener.properties]
notification_endpoint = "https://wso2am:9443/internal/data/v1/notify"
username = "${admin.username}"
password = "${admin.password}"
'header.X-WSO2-KEY-MANAGER' = "WSO2 IS"

# OAuth Token Configuration - Include user claims in JWT access tokens
[oauth.token_validation]
include_validation_context_as_jwt_in_reponse = "true"
validation_response_jwt_validity = "15m"

# Include user attributes in access tokens
[oauth.oidc.user_info]
claim_retriever = "default"
user_endpoint_claim_cache.enable = true

# JWT Token Generation - Include user claims
[oauth.token_generation]
access_token_type = "self_contained"
access_token_value_type = "JWT"
include_user_domain = false

# User claim configuration for JWT tokens
[[oauth.custom_claim_callback]]
class = "org.wso2.carbon.identity.oauth2.token.OAuthDefaultTokenIssuerImpl"

# Enable additional claims in JWT
[oauth.oidc.claims]
return_only_mapped_claims = false
